// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/adm/auth/edit": {
            "post": {
                "tags": [
                    "auth-登陆认证"
                ],
                "summary": "修改个人信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "号码",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/auth/get": {
            "get": {
                "tags": [
                    "auth-登陆认证"
                ],
                "summary": "获取登录信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "凭证",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/auth/passwd": {
            "post": {
                "tags": [
                    "auth-登陆认证"
                ],
                "summary": "修改自己的密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "旧密码",
                        "name": "opasswd",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新密码",
                        "name": "npasswd",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/cate/add": {
            "post": {
                "tags": [
                    "cate-分类"
                ],
                "summary": "添加分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Cate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/cate/drop": {
            "post": {
                "tags": [
                    "cate-分类"
                ],
                "summary": "通过id删除单条分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/cate/edit": {
            "post": {
                "tags": [
                    "cate-分类"
                ],
                "summary": "修改分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Cate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/cron/add": {
            "post": {
                "tags": [
                    "CronTask-定时任务"
                ],
                "summary": "添加定时任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CronTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/cron/drop": {
            "post": {
                "tags": [
                    "CronTask-定时任务"
                ],
                "summary": "通过id删除定时任务，支持多选",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/cron/edit": {
            "post": {
                "tags": [
                    "CronTask-定时任务"
                ],
                "summary": "修改定时任务参数",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Tag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/dict/add": {
            "post": {
                "tags": [
                    "dict"
                ],
                "summary": "添加字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Dict"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/dict/drop": {
            "post": {
                "tags": [
                    "dict"
                ],
                "summary": "通过key删除单条字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/dict/edit": {
            "post": {
                "tags": [
                    "dict"
                ],
                "summary": "修改字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Dict"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/global/edit": {
            "post": {
                "tags": [
                    "global-全局配置"
                ],
                "summary": "编辑global信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Global"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/page/add": {
            "post": {
                "tags": [
                    "page-页面"
                ],
                "summary": "添加页面",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Page"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/page/drop": {
            "post": {
                "tags": [
                    "page-页面"
                ],
                "summary": "通过id删除单条页面",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/page/edit": {
            "post": {
                "tags": [
                    "page-页面"
                ],
                "summary": "修改页面",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Page"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/post/add": {
            "post": {
                "tags": [
                    "post-文章"
                ],
                "summary": "添加文章",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Post"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/post/drop": {
            "post": {
                "tags": [
                    "post-文章"
                ],
                "summary": "通过id删除单条文章",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/post/edit": {
            "post": {
                "tags": [
                    "post-文章"
                ],
                "summary": "修改文章",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Post"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/status/app": {
            "get": {
                "tags": [
                    "status-状态信息"
                ],
                "summary": "获取服务器go信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.State"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/status/goinfo": {
            "get": {
                "tags": [
                    "status-状态信息"
                ],
                "summary": "获取服务器go信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Goinfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/tag/add": {
            "post": {
                "tags": [
                    "tag-标签"
                ],
                "summary": "添加标签",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Tag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/tag/drop": {
            "post": {
                "tags": [
                    "tag-标签"
                ],
                "summary": "通过id删除单条标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/tag/edit": {
            "post": {
                "tags": [
                    "tag-标签"
                ],
                "summary": "修改标签",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Tag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adm/upload/image": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "ctrl-系统相关"
                ],
                "summary": "上传图片并裁剪",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/analysis/log": {
            "post": {
                "tags": [
                    "Analysis-解析记录"
                ],
                "summary": "新增解析记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "请求数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AnalysisLog"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "auth-登陆认证"
                ],
                "summary": "登陆",
                "parameters": [
                    {
                        "type": "string",
                        "default": "zxysilent",
                        "description": "账号",
                        "name": "num",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "zxyslt",
                        "description": "密码",
                        "name": "pass",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "tags": [
                    "auth-登陆认证"
                ],
                "summary": "注销登录",
                "responses": {}
            }
        },
        "/api/auth/vcode": {
            "get": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "auth-登陆认证"
                ],
                "summary": "验证码",
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/cate/all": {
            "get": {
                "tags": [
                    "cate-分类"
                ],
                "summary": "获取所有分类",
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Cate"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/cate/get": {
            "get": {
                "tags": [
                    "cate-分类"
                ],
                "summary": "通过id获取单条分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Cate"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/cate/page": {
            "get": {
                "tags": [
                    "cate-分类"
                ],
                "summary": "获取分类分页",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "分页数",
                        "name": "pi",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "每页条数",
                        "name": "ps",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Cate"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/cron/page": {
            "get": {
                "tags": [
                    "CronTask-定时任务"
                ],
                "summary": "获取定时任务分页",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "分页数",
                        "name": "pi",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "每页条数",
                        "name": "ps",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Tag"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/dict/get": {
            "get": {
                "tags": [
                    "dict"
                ],
                "summary": "通过id获取单条字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Dict"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/dict/page": {
            "get": {
                "tags": [
                    "dict"
                ],
                "summary": "获取字典分页",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "分类id",
                        "name": "cid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "分页数",
                        "name": "pi",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "每页条数[5,30]",
                        "name": "ps",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Dict"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/global/get": {
            "get": {
                "tags": [
                    "global-全局配置"
                ],
                "summary": "获取global信息",
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Global"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/page/get": {
            "get": {
                "tags": [
                    "page-页面"
                ],
                "summary": "通过id获取单条页面",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Page"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/post/get": {
            "get": {
                "tags": [
                    "post-文章"
                ],
                "summary": "通过id获取单条文章",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Post"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/post/page": {
            "get": {
                "tags": [
                    "post-文章"
                ],
                "summary": "获取文章分页",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "分类id",
                        "name": "cate_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "分页数",
                        "name": "pi",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "每页条数",
                        "name": "ps",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Post"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/tag/all": {
            "get": {
                "tags": [
                    "tag-标签"
                ],
                "summary": "获取所有标签",
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Tag"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/tag/get": {
            "get": {
                "tags": [
                    "tag-标签"
                ],
                "summary": "通过id获取单条标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Tag"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/tag/page": {
            "get": {
                "tags": [
                    "tag-标签"
                ],
                "summary": "获取标签分页",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "分页数",
                        "name": "pi",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "每页条数",
                        "name": "ps",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Reply"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Tag"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AnalysisLog": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "msg": {
                    "description": "解析链接",
                    "type": "string"
                },
                "result": {
                    "description": "解析结果",
                    "type": "boolean"
                },
                "time": {
                    "description": "创建时间",
                    "type": "string"
                }
            }
        },
        "model.Cate": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "intro": {
                    "description": "描述",
                    "type": "string"
                },
                "name": {
                    "description": "分类名",
                    "type": "string"
                }
            }
        },
        "model.CronTask": {
            "type": "object",
            "properties": {
                "callFunc": {
                    "description": "执行函数",
                    "type": "string"
                },
                "content": {
                    "description": "cron表达式",
                    "type": "string"
                },
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "name": {
                    "description": "标签名",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                }
            }
        },
        "model.Dict": {
            "type": "object",
            "properties": {
                "inner": {
                    "description": "内部",
                    "type": "boolean"
                },
                "intro": {
                    "description": "说明",
                    "type": "string"
                },
                "key": {
                    "description": "key",
                    "type": "string"
                },
                "value": {
                    "description": "值",
                    "type": "string"
                }
            }
        },
        "model.Global": {
            "type": "object",
            "properties": {
                "analytic": {
                    "description": "统计脚本",
                    "type": "string"
                },
                "author": {
                    "description": "网站作者",
                    "type": "string"
                },
                "beian_miit": {
                    "description": "ICP备案",
                    "type": "string"
                },
                "beian_nism": {
                    "description": "公安备案",
                    "type": "string"
                },
                "comment": {
                    "description": "评论脚本",
                    "type": "string"
                },
                "copyright": {
                    "description": "版权",
                    "type": "string"
                },
                "description": {
                    "description": "网站描述",
                    "type": "string"
                },
                "favicon_url": {
                    "description": "Favicon地址",
                    "type": "string"
                },
                "github_url": {
                    "description": "githu地址",
                    "type": "string"
                },
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "keywords": {
                    "description": "网站关键词",
                    "type": "string"
                },
                "logo_url": {
                    "description": "Logo地址",
                    "type": "string"
                },
                "page_size": {
                    "description": "分页大小",
                    "type": "integer"
                },
                "site_css": {
                    "description": "全局css--以上为基本属性",
                    "type": "string"
                },
                "site_js": {
                    "description": "全局js",
                    "type": "string"
                },
                "site_url": {
                    "description": "网站地址",
                    "type": "string"
                },
                "title": {
                    "description": "网站标题",
                    "type": "string"
                },
                "weibo_url": {
                    "description": "微博地址",
                    "type": "string"
                }
            }
        },
        "model.Goinfo": {
            "type": "object",
            "properties": {
                "arch": {
                    "type": "string"
                },
                "num_cpu": {
                    "type": "integer"
                },
                "os": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "model.Page": {
            "type": "object",
            "properties": {
                "mult": {
                    "description": "多条件信息",
                    "type": "string"
                },
                "pi": {
                    "description": "分页页码",
                    "type": "integer"
                },
                "ps": {
                    "description": "分页大小",
                    "type": "integer"
                }
            }
        },
        "model.Post": {
            "type": "object",
            "properties": {
                "allow": {
                    "description": "允许评论",
                    "type": "boolean"
                },
                "cate": {
                    "description": "分类",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Cate"
                        }
                    ]
                },
                "cate_id": {
                    "description": "分类Id",
                    "type": "integer"
                },
                "created": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "kind": {
                    "description": "类型1-文章，2-页面",
                    "type": "integer"
                },
                "markdown": {
                    "description": "markdown内容",
                    "type": "string"
                },
                "path": {
                    "description": "访问路径",
                    "type": "string"
                },
                "richtext": {
                    "description": "富文本内容",
                    "type": "string"
                },
                "status": {
                    "description": "状态1-草稿，2-已发布",
                    "type": "integer"
                },
                "summary": {
                    "description": "摘要",
                    "type": "string"
                },
                "tags": {
                    "description": "标签",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Tag"
                    }
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "updated": {
                    "description": "修改时间",
                    "type": "string"
                }
            }
        },
        "model.Reply": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "msg": {
                    "type": "string",
                    "example": "提示信息"
                }
            }
        },
        "model.State": {
            "type": "object",
            "properties": {
                "cate": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "post": {
                    "type": "integer"
                },
                "tag": {
                    "type": "integer"
                }
            }
        },
        "model.Tag": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "intro": {
                    "description": "描述",
                    "type": "string"
                },
                "name": {
                    "description": "标签名",
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "ctime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "ecount": {
                    "description": "错误次数",
                    "type": "integer"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "ltime": {
                    "description": "上次登录时间",
                    "type": "string"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "num": {
                    "description": "账号",
                    "type": "string"
                },
                "openid_qq": {
                    "description": "qq",
                    "type": "string"
                },
                "passwd": {
                    "description": "密码",
                    "type": "string"
                },
                "phone": {
                    "description": "电话号码",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Blog’s 接口文档",
	Description:      "token传递方式包括[get/post]token、[header]Authorization\n/api/* 公共访问\n/adm/* 必须传入 token",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
